services:
  - type: web
    name: tox-pred-platform
    env: docker
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: 8125
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-02-15-preview
      - key: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: python
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
